name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: swift test -v

